using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using CunSorter.Models;

namespace CunSorter.Services;

/// <summary>
/// Takes the result-screen screenshot itself, replacing the external capture
/// tool: when the memory reader signals a song just ended, poll-grab the game
/// window (plain screen copy — the game runs borderless) until the frame looks
/// like the settlement screen, wait for the score tally animation to finish,
/// then save the PNG into the screenshots folder. The judgment data comes from
/// memory, so the new screenshot is classified without any OCR.
///
/// "Looks like the settlement screen" = two checks combined: a 17-point
/// UI-chrome pixel fingerprint (bit-stable across the archived result
/// screenshots; rejects gameplay ~9/17 and the map screen ~11/17; generated by
/// tools/gen_result_signature.py) AND the judgment-detail panel region mean
/// (rejects the CLEAR transition screen, which shares all the chrome).
/// Coordinates are 1920×1080 and scale proportionally.
/// </summary>
public sealed class CaptureService
{
    private static readonly (int X, int Y, int R, int G, int B)[] Signature =
    {
        (80, 168, 8, 174, 247), (1800, 208, 3, 198, 242), (1328, 40, 9, 216, 245),
        (64, 16, 239, 16, 16), (696, 24, 250, 210, 33), (1128, 40, 189, 52, 254),
        (760, 24, 231, 193, 35), (1752, 288, 223, 233, 253), (88, 648, 250, 235, 253),
        (40, 688, 252, 254, 255), (1896, 944, 255, 252, 255), (64, 272, 254, 254, 252),
        (24, 408, 255, 254, 255), (1848, 960, 255, 254, 254), (1752, 48, 255, 255, 255),
        (376, 32, 214, 219, 222), (1552, 16, 201, 200, 200),
    };
    private const int MatchTol = 24;      // per-channel tolerance
    private const int MatchNeed = 16;     // of 17 points (results: 17/17, gameplay: 9/17)
    private const int PollMs = 500;

    // Second discriminator: the CLEAR transition screen shares ALL the top
    // chrome with the result screen, so the 17 points can't tell them apart —
    // that is exactly what got mis-captured in production. The result screen
    // however has a large dark-purple judgment-detail panel mid-screen where
    // CLEAR shows near-white background. Mean RGB of that block is
    // (106,46,177) within ±20 on 231/235 archived results (the outliers are
    // the 表示切替 alternate view); CLEAR / gameplay / map frames deviate by
    // ≥90 on at least one channel.
    private static readonly (int X1, int Y1, int X2, int Y2) JudgePanelRect = (640, 665, 900, 845);
    private const int JudgePanelR = 106, JudgePanelG = 46, JudgePanelB = 177;
    private const int JudgePanelTol = 45;

    private readonly Func<CunConfig> _getCfg;
    private readonly Action<string, JudgeCounts> _onCaptured;   // (saved path, final counts)
    private readonly Action<string> _onStatus;
    private int _busy;
    private JudgeCounts _lastCaptured;                  // dedupe: one shot per song

    public CaptureService(Func<CunConfig> getCfg,
        Action<string, JudgeCounts> onCaptured, Action<string> onStatus)
    {
        _getCfg = getCfg;
        _onCaptured = onCaptured;
        _onStatus = onStatus;
    }

    /// <summary>Called when the counters freeze at song end (result screen is up
    /// while the counter block is still alive) and again, as a backstop, on the
    /// settle signal. One attempt at a time; a song that was already archived
    /// (same final counts) is skipped.</summary>
    public void RequestCapture(JudgeCounts final)
    {
        if (final == _lastCaptured) return;
        if (Interlocked.CompareExchange(ref _busy, 1, 0) != 0) return;
        _ = Task.Run(async () =>
        {
            try { await CaptureLoopAsync(final); }
            catch (Exception e) { Status($"截图失败：{e.Message}"); }
            finally { Interlocked.Exchange(ref _busy, 0); }
        });
    }

    private void Status(string s)
    {
        try { _onStatus(s); } catch { /* ignore */ }
    }

    private async Task CaptureLoopAsync(JudgeCounts final)
    {
        var cfg = _getCfg();
        var start = DateTime.UtcNow;
        var deadline = start.AddSeconds(Math.Max(5, cfg.Capture.TimeoutS));
        int best = -1;                                   // best signature score seen, for diagnostics
        bool chromeButNoPanel = false;                   // fingerprint hit while the judge panel didn't
        Bitmap? bestFrame = null;                        // kept so a timeout can dump it for analysis
        try
        {
        while (DateTime.UtcNow < deadline)
        {
            using (var frame = Grab(cfg.GameProcess))
            {
                if (frame != null)
                {
                    int score = SignatureScore(frame);
                    if (score >= MatchNeed && !JudgePanelLooksRight(frame)) chromeButNoPanel = true;
                    if (score > best)
                    {
                        best = score;
                        bestFrame?.Dispose();
                        bestFrame = (Bitmap)frame.Clone();
                    }
                }
                if (frame != null && IsResultScreen(frame))
                {
                    // The chrome is up but the score tally may still be rolling —
                    // give the animation time, then re-verify and keep THAT frame.
                    await Task.Delay(TimeSpan.FromSeconds(Math.Clamp(cfg.Capture.DelayS, 0, 15)));
                    using var settled = Grab(cfg.GameProcess);
                    if (settled != null && IsResultScreen(settled))
                    {
                        var path = SavePng(settled, cfg.ScreenshotsDir);
                        _lastCaptured = final;
                        Status($"已截取结算画面 {Path.GetFileName(path)}（触发后 {(DateTime.UtcNow - start).TotalSeconds:F1}s）");
                        try { _onCaptured(path, final); } catch { /* ignore */ }
                        return;
                    }
                }
            }
            await Task.Delay(PollMs);
        }
        if (best < 0)
        {
            Status("未捕获：拿不到游戏画面（窗口不在？）");
        }
        else
        {
            // Dump the best frame so the near-miss can be analysed offline
            // (which fingerprint points failed, and by how much).
            string note = "";
            try
            {
                var dir = Path.Combine(ConfigService.Here, "diag");
                Directory.CreateDirectory(dir);
                var dump = Path.Combine(dir,
                    $"capture_{DateTime.Now:yyyyMMdd_HHmmss}_best{best}.png");
                bestFrame!.Save(dump, ImageFormat.Png);
                note = $"，最佳帧已存 diag\\{Path.GetFileName(dump)}";
            }
            catch { /* diagnostics only */ }
            var hint = chromeButNoPanel ? "；指纹命中但判定面板未匹配（停在 CLEAR 过场/切换视图？）" : "";
            Status($"未捕获到结算画面（超时；最高指纹得分 {best}/{Signature.Length}{hint}{note}）");
        }
        }
        finally { bestFrame?.Dispose(); }
    }

    private static string SavePng(Bitmap bmp, string dir)
    {
        Directory.CreateDirectory(dir);
        var b = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
        var path = Path.Combine(dir, b + ".png");
        for (int i = 2; File.Exists(path); i++)
            path = Path.Combine(dir, $"{b}_{i}.png");
        bmp.Save(path, ImageFormat.Png);
        return path;
    }

    // ----------------------------- frame check --------------------------------
    private static bool IsResultScreen(Bitmap bmp) =>
        SignatureScore(bmp) >= MatchNeed && JudgePanelLooksRight(bmp);

    private static bool JudgePanelLooksRight(Bitmap bmp)
    {
        double sx = bmp.Width / 1920.0, sy = bmp.Height / 1080.0;
        int x1 = (int)(JudgePanelRect.X1 * sx), x2 = Math.Min((int)(JudgePanelRect.X2 * sx), bmp.Width);
        int y1 = (int)(JudgePanelRect.Y1 * sy), y2 = Math.Min((int)(JudgePanelRect.Y2 * sy), bmp.Height);
        long r = 0, g = 0, b = 0, n = 0;
        for (int y = y1; y < y2; y += 4)
            for (int x = x1; x < x2; x += 4)
            {
                var c = bmp.GetPixel(x, y);
                r += c.R; g += c.G; b += c.B; n++;
            }
        if (n == 0) return false;
        return Math.Abs(r / n - JudgePanelR) <= JudgePanelTol &&
               Math.Abs(g / n - JudgePanelG) <= JudgePanelTol &&
               Math.Abs(b / n - JudgePanelB) <= JudgePanelTol;
    }

    private static int SignatureScore(Bitmap bmp)
    {
        double sx = bmp.Width / 1920.0, sy = bmp.Height / 1080.0;
        int hit = 0;
        foreach (var (x, y, r, g, b) in Signature)
        {
            int px = Math.Min((int)(x * sx), bmp.Width - 1);
            int py = Math.Min((int)(y * sy), bmp.Height - 1);
            var c = bmp.GetPixel(px, py);
            if (Math.Abs(c.R - r) <= MatchTol && Math.Abs(c.G - g) <= MatchTol &&
                Math.Abs(c.B - b) <= MatchTol)
                hit++;
        }
        return hit;
    }

    // ----------------------------- grabbing -----------------------------------
    /// <summary>Screen-copy the game window's client area (borderless window ⇒
    /// screen content IS the game). Null when the game/window is unavailable.</summary>
    private static Bitmap? Grab(string processName)
    {
        var bare = processName.EndsWith(".exe", StringComparison.OrdinalIgnoreCase)
            ? processName[..^4] : processName;
        if (string.IsNullOrWhiteSpace(bare)) bare = "chusanApp";
        IntPtr hwnd;
        try
        {
            var ps = System.Diagnostics.Process.GetProcessesByName(bare);
            if (ps.Length == 0) return null;
            hwnd = ps[0].MainWindowHandle;
        }
        catch { return null; }
        if (hwnd == IntPtr.Zero) return null;

        if (!GetClientRect(hwnd, out var rc)) return null;
        int w = rc.Right - rc.Left, h = rc.Bottom - rc.Top;
        if (w < 640 || h < 360) return null;             // minimized / bogus
        var origin = new NativePoint { X = 0, Y = 0 };
        if (!ClientToScreen(hwnd, ref origin)) return null;

        try
        {
            var bmp = new Bitmap(w, h, PixelFormat.Format24bppRgb);
            using var g = Graphics.FromImage(bmp);
            g.CopyFromScreen(origin.X, origin.Y, 0, 0, new Size(w, h));
            return bmp;
        }
        catch { return null; }                            // secure desktop / lock screen
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativeRect { public int Left, Top, Right, Bottom; }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativePoint { public int X, Y; }

    [DllImport("user32.dll")]
    private static extern bool GetClientRect(IntPtr hwnd, out NativeRect rect);

    [DllImport("user32.dll")]
    private static extern bool ClientToScreen(IntPtr hwnd, ref NativePoint point);
}
